-- Supabase schema for mi-ecommerce demo

-- Products table (publicly readable)
CREATE TABLE IF NOT EXISTS products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  price text,
  image text,
  category text,
  created_at timestamptz DEFAULT now()
);

-- Orders table (recommended to use server side or service_role for inserts)
CREATE TABLE IF NOT EXISTS orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text NOT NULL,
  customer_email text,
  notes text,
  items jsonb NOT NULL,
  total numeric,
  status text DEFAULT 'pending',
  created_at timestamptz DEFAULT now()
);

-- Example seed data for products
INSERT INTO products (title, description, price, image, category) VALUES
('Vino Tinto Reserva', 'Vino excepcional con notas de cereza', '29.00', 'https://images.unsplash.com/photo-1547592166-5e3adfeba12b?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=0d1116f9c9c4d7e1563fd2c2e06b2bb8', 'Vinos'),
('Cava Brut', 'Cava ideal para celebraciones', '19.00', 'https://images.unsplash.com/photo-1514361892637-a5c40f7a2b96?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=9b460cbe7268d6ed09c6d086da58d7b9', 'Vinos'),
('Casa rural fin de semana', 'Disfruta un fin de semana en una casa rural', '199.00', 'https://images.unsplash.com/photo-1505691723518-36a6f3b4b3a9?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3&s=af3e7b2f1539a5cc8a4b05eefa9ed8f9', 'Renta');

-- Notes:
-- 1) Run these statements in the Supabase SQL editor (https://app.supabase.com/project/<your-project>/sql)
-- 2) By default "products" is readable via anon key. For inserting orders from client you need to:
--    - Create an RLS policy to allow inserts OR
--    - Use a server-side endpoint (recommended) that uses the service_role key to write orders (safer).
-- 3) Example RLS policy (NOT RECOMMENDED for public projects):
--    ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
--    CREATE POLICY "allow_insert_orders" ON orders FOR INSERT USING (true) WITH CHECK (true);
-- Replace with secure server-side flows for production.
